/**
 * Copyright 2026 Arm Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as assert from 'assert';
import * as fs from 'fs';
import * as net from 'net';
import * as os from 'os';
import * as path from 'path';
import { attachEndpoints, isListening, silentAttachEndpoints } from '../core/gdbServerPorts';

/** A launch.json as CMSIS Solution writes it: a launch and an attach configuration, with a comment. */
function launchJson(port: number | string, host?: string): string {
    return `{
    // generated by CMSIS Solution
    "version": "0.2.0",
    "configurations": [
        { "name": "STLink@pyOCD (launch)", "type": "gdbtarget", "request": "launch", "target": { "server": "pyocd", "port": "3333" } },
        { "name": "STLink@pyOCD (attach)", "type": "gdbtarget", "request": "attach", "target": { ${host ? `"host": "${host}", ` : ''}"port": ${JSON.stringify(port)} } },
        { "name": "Python", "type": "debugpy", "request": "attach", "connect": { "port": 5678 } },
    ]
}`;
}

/** A port nothing listens on: bound once, then closed. */
async function closedPort(): Promise<number> {
    const server = net.createServer();
    await new Promise<void>((ready) => server.listen(0, '127.0.0.1', ready));
    const port = (server.address() as net.AddressInfo).port;
    await new Promise<void>((done) => server.close(() => done()));
    return port;
}

/**
 * Where a CMSIS attach connects and whether a GDB server listens there: an
 * attach with none fails after GDB's 15 s connect timeout with a modal
 * "could not connect: Operation timed out." dialog, so cmsis_action refuses
 * it first.
 */
suite('GDB server ports of the attach configurations', () => {
    test('only gdbtarget attach configurations with a numeric port count; the host defaults to localhost', () => {
        assert.deepStrictEqual(attachEndpoints(launchJson('50000')), [{ name: 'STLink@pyOCD (attach)', host: 'localhost', port: 50000 }]);
        assert.deepStrictEqual(attachEndpoints(launchJson(2331, '192.168.1.7')), [{ name: 'STLink@pyOCD (attach)', host: '192.168.1.7', port: 2331 }]);
        assert.deepStrictEqual(attachEndpoints(launchJson('${config:port}')), []);
        assert.deepStrictEqual(attachEndpoints(launchJson(70000)), []);
        assert.deepStrictEqual(attachEndpoints('not json'), []);
        assert.deepStrictEqual(attachEndpoints('{"configurations": 3}'), []);
    });

    test('a listening port answers, a closed one does not, and neither rejects', async () => {
        const server = net.createServer((socket) => socket.destroy());
        await new Promise<void>((ready) => server.listen(0, '127.0.0.1', ready));
        try {
            const port = (server.address() as net.AddressInfo).port;
            assert.strictEqual(await isListening('127.0.0.1', port), true);
        } finally {
            await new Promise<void>((done) => server.close(() => done()));
        }
        assert.strictEqual(await isListening('127.0.0.1', await closedPort()), false);
    });

    test('silentAttachEndpoints names the silent endpoints, and nothing when one listens or there is nothing to check', async () => {
        const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cda-attach-'));
        try {
            assert.strictEqual(await silentAttachEndpoints(dir), undefined, 'no launch.json');
            fs.mkdirSync(path.join(dir, '.vscode'));
            const silent = await closedPort();
            fs.writeFileSync(path.join(dir, '.vscode', 'launch.json'), launchJson(silent, '127.0.0.1'));
            assert.deepStrictEqual(await silentAttachEndpoints(dir), [{ name: 'STLink@pyOCD (attach)', host: '127.0.0.1', port: silent }]);

            const server = net.createServer((socket) => socket.destroy());
            await new Promise<void>((ready) => server.listen(0, '127.0.0.1', ready));
            try {
                fs.writeFileSync(path.join(dir, '.vscode', 'launch.json'), launchJson((server.address() as net.AddressInfo).port, '127.0.0.1'));
                assert.strictEqual(await silentAttachEndpoints(dir), undefined, 'a server listens');
            } finally {
                await new Promise<void>((done) => server.close(() => done()));
            }
            fs.writeFileSync(path.join(dir, '.vscode', 'launch.json'), '{"configurations": []}');
            assert.strictEqual(await silentAttachEndpoints(dir), undefined, 'no attach configuration');
        } finally {
            fs.rmSync(dir, { recursive: true, force: true });
        }
    });
});
